#!/bin/sh -ex

if [ "$TRAVIS_BRANCH" != "master" ] || [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
	echo "$0: skipping: not build master branch on travis-ci"
	exit 0
fi

TMP=${TMP:-/tmp}

OUTPUT_REPO="https://strdeploy:${GH_TOKEN}@github.com/sharethrough/Android-SDK-Maven.git"
(
cd ${TMP}
rm -rf maven || true
git clone ${OUTPUT_REPO} maven
)

pwd
OUTPUT="${TMP}/maven/sharethrough-android-sdk-${TRAVIS_BUILD_NUMBER}"
cp build/outputs/aar/*.aar "${OUTPUT}.aar"
cp build/distributions/*.zip "${OUTPUT}.zip"
cd "${TMP}/maven"

git config --global user.email "travis-ci@sharethrough.com"
git config --global user.name "Automated Build"

BUILD_NUMBER=$((238 + $TRAVIS_BUILD_NUMBER))
git add .
git commit -m "Travis build ${BUILD_NUMBER}"

git remote rm origin
git remote add origin ${OUTPUT_REPO}

git push origin master